import numpy as np
import matplotlib.pyplot as plt
from config import default_objects, FIG_DIR, DATA_DIR, DYN_PER_CM2_TO_MMHG
from io_utils import finalize_figure, save_json, save_spectrum_csv
from core_impedance import structured_tree_spectrum, resistance_spectrum, rcr_spectrum, fit_rcr_to_tree, reflection_coefficient_spectrum, build_time_array, synthetic_inflow_waveform, pressure_from_impedance
blood, wall, tree, config = default_objects()
freqs = np.linspace(0, config.f_max_hz, config.n_freqs)
z_tree = structured_tree_spectrum(freqs, tree, blood, wall)
R_dc = float(np.real(z_tree[0]))
z_R = resistance_spectrum(freqs, R_dc)
Rp, C, Rd = fit_rcr_to_tree(freqs, z_tree, config.rcr_fit_fmax_hz)
z_RCR = rcr_spectrum(freqs, Rp, C, Rd)
gamma_tree = reflection_coefficient_spectrum(freqs, z_tree, tree, blood, wall)
save_spectrum_csv(DATA_DIR / 'deterministic_spectra.csv', freqs, [('R', z_R), ('RCR', z_RCR), ('structured_tree', z_tree), ('gamma_tree', gamma_tree)])
mask = freqs > 0
plt.figure(figsize=(7.5, 4.5))
plt.plot(freqs[mask], abs(z_R[mask]), label='R', linewidth=2.2)
plt.plot(freqs[mask], abs(z_RCR[mask]), label='RCR', linewidth=2.2)
plt.plot(freqs[mask], abs(z_tree[mask]), label='Structured tree', linewidth=2.2)
plt.xlabel('Frequency [Hz]')
plt.ylabel('$|Z(\\omega)|$')
plt.title('Impedance modulus')
plt.legend()
plt.grid(alpha=0.3)
finalize_figure(FIG_DIR / '02_impedance_modulus.png')
plt.figure(figsize=(7.5, 4.5))
plt.plot(freqs[mask], np.angle(z_R[mask], deg=True), label='R', linewidth=2.2)
plt.plot(freqs[mask], np.angle(z_RCR[mask], deg=True), label='RCR', linewidth=2.2)
plt.plot(freqs[mask], np.angle(z_tree[mask], deg=True), label='Structured tree', linewidth=2.2)
plt.xlabel('Frequency [Hz]')
plt.ylabel('Phase [deg]')
plt.title('Impedance phase')
plt.legend()
plt.grid(alpha=0.3)
finalize_figure(FIG_DIR / '03_impedance_phase.png')
plt.figure(figsize=(7.5, 4.5))
plt.plot(freqs[mask], abs(gamma_tree[mask]), color='black', linewidth=2.2)
plt.xlabel('Frequency [Hz]')
plt.ylabel('$|\\Gamma(\\omega)|$')
plt.title('Structured-tree reflection coefficient')
plt.grid(alpha=0.3)
finalize_figure(FIG_DIR / '04_reflection_coefficient.png')
t = build_time_array(config)
q = synthetic_inflow_waveform(t, config.cycle_length_s)
fft_freqs = np.fft.rfftfreq(len(t), d=config.dt)
z_tree_td = structured_tree_spectrum(fft_freqs, tree, blood, wall)
z_R_td = resistance_spectrum(fft_freqs, R_dc)
z_RCR_td = rcr_spectrum(fft_freqs, Rp, C, Rd)
p_tree = pressure_from_impedance(t, q, z_tree_td) * DYN_PER_CM2_TO_MMHG
p_R = pressure_from_impedance(t, q, z_R_td) * DYN_PER_CM2_TO_MMHG
p_RCR = pressure_from_impedance(t, q, z_RCR_td) * DYN_PER_CM2_TO_MMHG
plt.figure(figsize=(7.5, 4.5))
plt.plot(t, p_R, label='R', linewidth=2.2)
plt.plot(t, p_RCR, label='RCR', linewidth=2.2)
plt.plot(t, p_tree, label='Structured tree', linewidth=2.2)
plt.xlabel('Time [s]')
plt.ylabel('Pressure [mmHg]')
plt.title('Proximal pressure waveforms')
plt.legend()
plt.grid(alpha=0.3)
finalize_figure(FIG_DIR / '05_pressure_waveforms.png')
save_json({'R_dc': R_dc, 'Rp': Rp, 'C': C, 'Rd': Rd, 'tree_peak_pressure_mmhg': float(np.max(p_tree)), 'tree_min_pressure_mmhg': float(np.min(p_tree)), 'tree_mean_pressure_mmhg': float(np.mean(p_tree)), 'tree_pulse_pressure_mmhg': float(np.max(p_tree) - np.min(p_tree)), 'R_peak_pressure_mmhg': float(np.max(p_R)), 'RCR_peak_pressure_mmhg': float(np.max(p_RCR))}, DATA_DIR / 'deterministic_summary.json')
print('Deterministic comparison done.')
